version: '3'
services:
  redis:
    image: 'redis:latest'
    container_name: 'redis-trending'
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'app-trending'
    ports:
      - '3000:3000'
    depends_on:
      - redis
